services:
  qualcoder:
    build: "."
    image: peterstory/qualcoder-sshd:3.5
    environment:
      - ROOT_PASSWORD
    ports:
      - "${LISTEN_SSHD}:22"
    volumes:
      - "./QualCoder:/root/QualCoder"
